- lib/webidl2.js
This makes it possible to run it in Workers.
> Define the WebIDL2 property on self rather than window.

- test/syntax/idl/callback.widl
- test/syntax/json/callback.json
Added this test as I thought I had identified an unsupported construct. Turns out it works, so might as well add the test. :)
> Add test for callback with multiple arguments.

- package.json
> Bump microtime to 2.1.1

- test/web/make-web-tests.js
> Correct jsondiffpatch location.

- lib/writer.js
Would you consider this commit which adds writer support for
- serializer
- iterable
- legacyiterable
- maplike
- setlike
- callback interface
Thanks!
> Expand writer support

- lib/webidl2.js
- lib/writer.js
- test/invalid/idl/record-key.widl
- test/invalid/json/record-key.json
- test/syntax/idl/record.widl
- test/syntax/json/record.json
> Add support for records

- README.md
> Add documentation for namespaces

- README.md
Follows #121. I forgot to update the docs, sorry!
> Remove iterator documentation

- lib/webidl2.js
- test/syntax/json/dictionary-inherits.json
- test/syntax/json/dictionary.json
- test/syntax/json/identifier-qualified-names.json
- test/syntax/json/typedef-union.json
- test/syntax/json/typedef.json
I thought we somewhere mentioned typedef-type but I couldn't find it.
> feat: add dictionary/typedef-type

- README.md
> Remove description about typePair

- package-lock.json
- package.json
I basically did `npm version patch && npm publish && git push` and then I realized I cannot directly push into the main branch anymore. Maybe I should do version bump in PRs...
> chore(package): bump version number to 10.3.3

- .gitmodules
- README.md
> tests: Remove test/widlproc

- lib/webidl2.js
I've felt bad about those two separate functions with nearly identical feature, so this PR merges them.
(Yeah... I myself caused the duplication. Sorry 😱)
> refactor: merge attribute functions

- lib/webidl2.js
- test/invalid/idl/spaced-negative-infinity.widl
- test/invalid/idl/spaced-variadic.widl
- test/invalid/json/spaced-negative-infinity.json
- test/invalid/json/spaced-variadic.json
Closes #162 
This is similar to #154 but for punctuations.
> fix: prevent incorrect spaced negative infinity and variadic marks

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/dictionary.json
- test/syntax/json/generic.json
- test/syntax/json/promise-void.json
- test/syntax/json/record.json
- test/syntax/json/sequence.json
- test/syntax/json/typedef.json
- test/syntax/json/typesuffixes.json
> Generics always as an array

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/dictionary-inherits.json
- test/syntax/json/extended-attributes.json
- test/syntax/json/generic.json
- test/syntax/json/inherits-getter.json
- test/syntax/json/interface-inherits.json
- test/syntax/json/namedconstructor.json
This changes type of `inheritance` field from string to object with `name` and `trivia` field.
> Add trivia for inheritance

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/allowany.json
- test/syntax/json/callback.json
- test/syntax/json/enum.json
- test/syntax/json/equivalent-decl.json
- test/syntax/json/generic.json
- test/syntax/json/getter-setter.json
- test/syntax/json/identifier-qualified-names.json
- test/syntax/json/implements.json
- test/syntax/json/indexed-properties.json
- test/syntax/json/namespace.json
- test/syntax/json/nointerfaceobject.json
- test/syntax/json/nullableobjects.json
- test/syntax/json/operation-optional-arg.json
- test/syntax/json/overloading.json
- test/syntax/json/overridebuiltins.json
- test/syntax/json/record.json
- test/syntax/json/reg-operations.json
- test/syntax/json/replaceable.json
- test/syntax/json/sequence.json
- test/syntax/json/static.json
- test/syntax/json/stringifier-custom.json
- test/syntax/json/stringifier.json
- test/syntax/json/treatasnull.json
- test/syntax/json/treatasundefined.json
- test/syntax/json/typedef.json
- test/syntax/json/typesuffixes.json
- test/syntax/json/variadic-operations.json
Adds `body` which now includes `idlType`, `name` and `arguments`.
> Add trivia for operation

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/allowany.json
- test/syntax/json/callback.json
- test/syntax/json/constructor.json
- test/syntax/json/enum.json
- test/syntax/json/equivalent-decl.json
- test/syntax/json/extended-attributes.json
- test/syntax/json/getter-setter.json
- test/syntax/json/identifier-qualified-names.json
- test/syntax/json/implements.json
- test/syntax/json/indexed-properties.json
- test/syntax/json/namedconstructor.json
- test/syntax/json/namespace.json
- test/syntax/json/nointerfaceobject.json
- test/syntax/json/nullableobjects.json
- test/syntax/json/operation-optional-arg.json
- test/syntax/json/overloading.json
- test/syntax/json/overridebuiltins.json
- test/syntax/json/record.json
- test/syntax/json/reg-operations.json
- test/syntax/json/sequence.json
- test/syntax/json/static.json
- test/syntax/json/treatasnull.json
- test/syntax/json/treatasundefined.json
- test/syntax/json/typedef.json
- test/syntax/json/typesuffixes.json
- test/syntax/json/variadic-operations.json
Happy to see more and more commits are merged for #185 😍
> Add trivia for arguments

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/constants.json
- test/syntax/json/dictionary-inherits.json
- test/syntax/json/dictionary.json
- test/syntax/json/nullable.json
- test/syntax/json/operation-optional-arg.json
> Add trivia for const member type

- lib/webidl2.js
- lib/writer.js
- test/invalid/json/extattr-empty-ids.json
- test/syntax/json/extended-attributes.json
The list now contains objects instead of strings.
> Add trivia for extended attribute identifiers

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/mixin.json
- test/syntax/json/namespace.json
> Add trivia for mixins and namespaces

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/callback.json
Countdown, 5, 4, 😁
Always thanks for your reviews!
> Add trivia for callbacks

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/implements.json
- test/syntax/json/mixin.json
Sad that we cannot remove `implements` yet...
> Add trivia for implements/includes

- README.md
Forgot to document them 😅
`trivia` will follow soon.
> Document generic array, escapedName and removal of sequence

- README.md
Hard to document everything in once 😅 so multiple PRs again.
I shouldn't have forgotten about this in previous PRs...
> Document trivia for interfaces/mixins/namespaces

- README.md
I think this is the last PR about `trivia`. 🎉
> Document changes for idlType and extAttrs

- lib/webidl2.js
- test/invalid/idl/operation-too-special.widl
- test/invalid/json/operation-too-special.json
> fix(lib/webidl): disallow multiple special keywords

- lib/webidl2.js
- test/syntax/json/enum.json
> fix: enum values should be of type enum-value

- package-lock.json
- package.json
(I was testing object spread syntax and found every version of eslint doesn't supports it yet 😮)
> chore(package): update eslint

- README.md
I tried JSDoc style here, hope this will be familiar enough...
> Add docs for template feature

- .eslintrc.json
- lib/webidl2.js
- lib/writer.js
> style: apply no-trailing-spaces

- .travis.yml
- lib/webidl2.js
- lib/writer.js
- test/writer.js
Slightly concerned about the code being longer because of `toJSON()` but I think each function is now more easy to read.
> refactor: includes as a class

- lib/webidl2.js
- lib/writer.js
- test/writer.js
> refactor: enum as a class

- lib/webidl2.js
- test/syntax/baseline/escaped-name.json
- test/syntax/baseline/escaped-type.json
- test/syntax/baseline/identifier-qualified-names.json
- test/syntax/baseline/mixin.json
- test/syntax/baseline/typedef-union.json
- test/syntax/baseline/typedef.json
> refactor(lib/webidl2): move toJSON to Definition

- lib/webidl2.js
- lib/writer.js
- test/syntax/baseline/dictionary-inherits.json
- test/syntax/baseline/dictionary.json
- test/syntax/baseline/enum.json
- test/syntax/baseline/escaped-type.json
- test/syntax/baseline/identifier-qualified-names.json
- test/syntax/baseline/typedef-union.json
- test/syntax/baseline/typedef.json
- test/writer.js
> refactor: field as a class

- lib/webidl2.js
- test/syntax/baseline/namespace.json
> refactor: namespace as a class

- lib/webidl2.js
- lib/writer.js
- test/syntax/baseline/iterable.json
- test/syntax/baseline/maplike.json
- test/syntax/baseline/setlike.json
- test/writer.js
Also adding missing object arguments (and tests for them) on the writer.
> refactor: iterable as a class

- test/syntax/baseline/nullable.json
- test/syntax/idl/nullable.widl
This is weird but a supported syntax anyway.
> test(lib/webidl2): nullable constant with typedef identifiers

- lib/webidl2.js
- lib/writer.js
- test/syntax/baseline/allowany.json
- test/syntax/baseline/constructor.json
- test/syntax/baseline/extended-attributes.json
- test/syntax/baseline/identifier-hyphen.json
- test/syntax/baseline/iterable.json
- test/syntax/baseline/maplike.json
- test/syntax/baseline/namedconstructor.json
- test/syntax/baseline/nointerfaceobject.json
- test/syntax/baseline/overloading.json
- test/syntax/baseline/overridebuiltins.json
- test/syntax/baseline/prototyperoot.json
- test/syntax/baseline/putforwards.json
- test/syntax/baseline/record.json
- test/syntax/baseline/replaceable.json
- test/syntax/baseline/sequence.json
- test/syntax/baseline/setlike.json
- test/syntax/baseline/stringifier-attribute.json
- test/syntax/baseline/stringifier-custom.json
- test/syntax/baseline/treatasnull.json
- test/syntax/baseline/treatasundefined.json
- test/syntax/baseline/typedef.json
- test/syntax/baseline/uniontype.json
A complex part of refactoring.
> refactor: extended attribute as a class

- lib/webidl2.js
- lib/writer.js
- test/syntax/baseline/allowany.json
- test/syntax/baseline/constructor.json
- test/syntax/baseline/extended-attributes.json
- test/syntax/baseline/identifier-hyphen.json
- test/syntax/baseline/iterable.json
- test/syntax/baseline/maplike.json
- test/syntax/baseline/namedconstructor.json
- test/syntax/baseline/nointerfaceobject.json
- test/syntax/baseline/overloading.json
- test/syntax/baseline/overridebuiltins.json
- test/syntax/baseline/prototyperoot.json
- test/syntax/baseline/putforwards.json
- test/syntax/baseline/record.json
- test/syntax/baseline/replaceable.json
- test/syntax/baseline/sequence.json
- test/syntax/baseline/setlike.json
- test/syntax/baseline/stringifier-attribute.json
- test/syntax/baseline/stringifier-custom.json
- test/syntax/baseline/treatasnull.json
- test/syntax/baseline/treatasundefined.json
- test/syntax/baseline/typedef.json
- test/syntax/baseline/uniontype.json
The `list()` helper will be used in several more places.
> refactor: extended attributes as a class

- lib/webidl2.js
- test/invalid/baseline/frozenarray-empty.txt
- test/invalid/baseline/promise-empty.txt
- test/invalid/baseline/sequence-empty.txt
- test/invalid/idl/frozenarray-empty.widl
- test/invalid/idl/promise-empty.widl
- test/invalid/idl/sequence-empty.widl
> fix(lib/webidl2): disallow empty generic type

- lib/webidl2.js
- test/invalid/baseline/record-key.txt
- test/syntax/baseline/record.json
Reaching to the end of this work 🚴‍♀️
> refactor: generic type as a class

- checker/index.html
Mostly whitespace changes. (I just did Control+Alt+F on VSCode...)
> feat: add validation feature to the checker page

- checker/index.html
> fix: update checker to use webpack build result

- checker/index.html
Because this is visually painful 🤣
> fix(checker): add an empty line between messages

- lib/webidl2.js
- test/invalid/baseline/float.txt
- test/invalid/idl/float.widl
- test/syntax/baseline/extended-attributes.json
Fixes #302, corresponds to https://github.com/heycam/webidl/issues/558.
> fix(webidl2): rename float as decimal

- lib/error.js
- lib/webidl2.js
- test/invalid.js
> fix(lib/webidl2): restore error fields

- lib/writer.js
- test/writer.js
Found while updating webidl2 on ReSpec.
> fix(lib/writer): call ts.trivia with actual string

- README.md
> docs(lib/writer): document generic()

- lib/productions/default.js
- lib/productions/helpers.js
- test/syntax/baseline/dictionary.json
- test/syntax/idl/dictionary.widl
See https://github.com/heycam/webidl/pull/750 for more information.
> feat(productions/default): support {} as a default value

- lib/productions/argument.js
- lib/productions/extended-attributes.js
- lib/productions/helpers.js
- lib/productions/type.js
- lib/webidl2.js
This is rather big but couldn't split them because of their dependencies.
> refactor(lib/webidl2): modularize types+extattrs 

- lib/productions/attribute.js
- lib/productions/operation.js
- lib/webidl2.js
- test/invalid/baseline/array.txt
- test/invalid/baseline/no-semicolon-operation.txt
- test/invalid/baseline/raises.txt
- test/invalid/idl/no-semicolon-operation.widl
- test/syntax/baseline/extended-attributes.json
- test/syntax/baseline/record.json
- test/syntax/baseline/typedef-union.json
- test/syntax/baseline/uniontype.json
> refactor(lib/webidl2): modularize attributes/operations

- lib/productions/constant.js
- lib/productions/field.js
- lib/productions/typedef.js
- lib/webidl2.js
- test/invalid/baseline/const-null.txt
- test/invalid/baseline/dict-field-unterminated.txt
- test/invalid/baseline/scopedname.txt
- test/invalid/baseline/spaced-negative-infinity.txt
- test/invalid/baseline/stringconstants.txt
> refactor(lib/webidl2): modularize const/field/typedef

- lib/productions/container.js
- lib/productions/dictionary.js
- lib/productions/helpers.js
- lib/productions/interface.js
- lib/productions/mixin.js
- lib/productions/namespace.js
- lib/webidl2.js
- test/invalid/baseline/id-underscored-number.txt
- test/invalid/baseline/inheritance-typeless.txt
- test/invalid/idl/inheritance-typeless.widl
The last part of modularization.
> refactor(lib/webidl2): modularize container types

- lib/validator.js
- test/invalid.js
A part of #347, so the batch validation can be more straightforward.
> feat(validation): support batch validation

- lib/validator.js
- lib/validators/helpers.js
- test/invalid/baseline/recursive-type.txt
- test/invalid/idl/recursive-type.webidl
Rather a serious issue 😱
Fixes #361
> fix(validation): prevent infinite recursion

- lib/error.js
- lib/productions/extended-attributes.js
- lib/tokeniser.js
- test/invalid.js
- test/invalid/baseline/exposed.txt
> feat(validation): warn about NoInterfaceObject

- .eslintrc.json
- package-lock.json
- package.json
Thanks to @munchkinhalfling for catching this problem! (#377, #378, #379)
We should probably also do this for ReSpec.
> chore(eslint): force file extensions for import statements

- README.md
I keep forgetting to update the docs 😅
> docs(error): add new fields

- README.md
> docs(README): update link to webidl spec

- checker/index.html
- lib/error.js
- lib/productions/argument.js
Copy-paste this IDL and face the magic:
```webidl
dictionary A {
short field;
};
interface ABC {
void op(optional A a);
};
```
> feat(checker): add autofix API

- lib/productions/extended-attributes.js
- lib/productions/helpers.js
- lib/productions/interface.js
- lib/productions/namespace.js
- test/autofix.js
The second frequent invalid thing in IDL world.
> feat(extAttrs): add autofix for Exposed=Window

- lib/productions/constructor.js
- lib/productions/interface.js
- test/autofix.js
- test/invalid/baseline/argument-dict-default.txt
- test/invalid/baseline/constructor.txt
- test/invalid/idl/argument-dict-default.webidl
- test/invalid/idl/constructor.webidl
> feat(validator): recommend constructor operations

- README.md
- lib/writer.js
> docs(README): describe constructor operations

- lib/error.js
- lib/productions/argument.js
- lib/productions/extended-attributes.js
- lib/productions/interface.js
- lib/productions/namespace.js
- lib/productions/operation.js
- lib/productions/type.js
- lib/validator.js
- lib/validators/interface.js
- test/invalid/baseline/constructor.txt
The first parameter was redundant.
> refactor(validator): reduce parameter count

- README.md
Currently it looks like we invented a new version of Web IDL, but we didn't! So this PR changes the title.
> docs(README): change the title

- lib/productions/helpers.js
- test/autofix.js
More frequent formatting.
PS: The `getLastIndentation` part is copy-pasted from #419.
> fix(productions/helpers): emit newline after [Exposed]

- lib/productions/helpers.js
- lib/productions/interface.js
- test/autofix.js
> fix(autofix): correct constructor ordering 2

- .github/pull_request_template.md
> chore(.github): add issue number placeholder

- README.md
- lib/productions/argument.js
- lib/productions/array-base.js
- lib/productions/attribute.js
- lib/productions/base.js
- lib/productions/callback.js
- lib/productions/constant.js
- lib/productions/constructor.js
- lib/productions/container.js
- lib/productions/default.js
- lib/productions/enum.js
- lib/productions/extended-attributes.js
- lib/productions/field.js
- lib/productions/helpers.js
- lib/productions/interface.js
- lib/productions/iterable.js
- lib/productions/operation.js
- lib/productions/type.js
- lib/productions/typedef.js
- lib/webidl2.js
- test/parent.js
WIP because I want everything to be less complex than this.
> feat: add `.parent` field

- README.md
- lib/productions/interface.js
- test/invalid/baseline/constructible-global.txt
- test/invalid/idl/constructible-global.webidl
This patch closes #337 and includes:
> feat(validators): warns about constructible globals

- .eslintrc.json
> chore(.eslintrc): force newline at the end of files

- README.md
- lib/productions/argument.js
- lib/productions/type.js
- lib/validator.js
- lib/validators/helpers.js
- test/autofix.js
- test/invalid/baseline/argument-dict-optional.txt
- test/invalid/idl/argument-dict-optional.webidl
- test/util/collect.js
Closes #407 
WIP, probably depends on #85 to check argument indices.
> feat(validator): check dictionary argument optionality

- jsconfig.json
- lib/error.js
- lib/productions/argument.js
- lib/productions/array-base.js
- lib/productions/base.js
- lib/productions/callback-interface.js
- lib/productions/constant.js
- lib/productions/constructor.js
- lib/productions/container.js
- lib/productions/dictionary.js
- lib/productions/enum.js
- lib/productions/field.js
- lib/productions/includes.js
- lib/productions/mixin.js
- lib/productions/namespace.js
- lib/productions/operation.js
- lib/productions/token.js
- lib/productions/typedef.js
- lib/supplement.d.ts
- lib/tokeniser.js
- lib/validator.js
- lib/validators/helpers.js
- lib/validators/interface.js
- lib/webidl2.js
- package-lock.json
- package.json
> refactor: add ts-check

- package.json
Per [the relevant Node.js documentation](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field). (See also [the blog post](https://medium.com/@nodejs/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663).)
> chore(package): add type field

- .github/workflows/nodejs.yml
Sad that we still don't have `lts/*` support. (https://github.com/actions/setup-node/issues/26)
> test: run on Node.js 13

- package-lock.json
- package.json
> chore(package): update deps

- README.md
- lib/productions/attribute.js
- lib/productions/base.js
- lib/productions/callback.js
- lib/productions/extended-attributes.js
- lib/productions/interface.js
- lib/productions/type.js
- test/autofix.js
- test/invalid/baseline/constructible-global.txt
- test/invalid/baseline/exposed.txt
- test/invalid/baseline/renamed-legacy-extattrs.txt
- test/invalid/idl/constructible-global.webidl
- test/invalid/idl/exposed.webidl
- test/invalid/idl/renamed-legacy-extattrs.webidl
This patch closes #463 and includes:
> feat: validate and autofix legacy extended attributes

- .github/FUNDING.yml
> chore: link to opencollective

- README.md
> docs: describe renamed-legacy

- lib/productions/iterable.js
- test/invalid/baseline/nullable-union-dictionary.txt
- test/invalid/idl/nullable-union-dictionary.webidl
> feat(productions/iterable): validate iterable types

- lib/error.js
- test/invalid/baseline/argument-dict-default.txt
- test/invalid/baseline/argument-dict-nullable.txt
- test/invalid/baseline/argument-dict-optional.txt
- test/invalid/baseline/exposed.txt
- test/invalid/baseline/nullable-union-dictionary.txt
- test/invalid/baseline/recursive-type.txt
- test/invalid/baseline/renamed-legacy-extattrs.txt
Sometimes only showing the leaf node name isn't really helpful to find the cause.
See also https://github.com/web-platform-tests/wpt/pull/23397#issuecomment-623752859
> feat(error): show context hierarchy

- lib/productions/type.js
- lib/tokeniser.js
- test/syntax/baseline/generic.json
- test/syntax/idl/generic.webidl
Corresponds to https://github.com/heycam/webidl/pull/840.
> feat(productions/type): support ObservableArray

- lib/productions/interface.js
- test/invalid/baseline/exposed.txt
- test/invalid/idl/exposed.webidl
Matches https://github.com/heycam/webidl/pull/920
> fix(validation): require [Exposed] for all concrete interfaces

- .github/dependabot.yml
This should reduce the distracting notifications 😄 (It's not that they are working actually, because of https://github.com/dependabot/dependabot-core/issues/2643 🙄)
> chore(dependabot): update weekly

- README.md
This replaces the previous dismissive language and thus tries being more inclusive.
Closes #502
> chore(README): add a single line description about Web IDL with a link

- .github/workflows/changelog.yml
Copied from @sidvishnoi's work in ReSpec 😅
> chore(.github/workflows): autogenerate changelogs

- README.md
- checker/index.html
> chore(checker): align to center etc.

- lib/productions/helpers.js
- lib/tokeniser.js
- test/invalid/baseline/bigint-keyword.txt
- test/invalid/idl/bigint-keyword.webidl
- test/syntax/baseline/bigint.json
- test/syntax/idl/bigint.webidl
Matches https://github.com/heycam/webidl/pull/525
> feat: support bigints

- README.md
This patch closes #529 and includes:
> chore(README): Describe the `inheritance` field consistently (#529)

- lib/productions/attribute.js
- lib/supplement.d.ts
- test/invalid/baseline/invalid-attribute.txt
- test/invalid/baseline/nullable-union-dictionary.txt
Originally just intended to add `@ts-check` and then found a bug 😄
> fix(productions/attribute): adjust validation pointer position

- README.md
- lib/productions/namespace.js
- test/syntax/baseline/namespace.json
- test/syntax/idl/namespace.webidl
This patch closes #589 and includes:
> feat(productions/namespace): allow constants

- README.md
- docs/custom-productions.md
- lib/tokeniser.js
- lib/webidl2.js
- test/custom-production.js
This patch closes #512 and includes:
> feat: support custom productions

- lib/validators/interface.js
- test/invalid/baseline/overloads.txt
- test/invalid/idl/overloads.webidl
This patch closes #672 and includes:
> Allow same named static and nonstatic operations
