w3c/webidl2.js

- lib/webidl2.js
- test/syntax/idl/generic.widl
- test/syntax/json/generic.json
This appears in the #attr-basic test case for ReSpec.
Fixes #19.
> Make `attribute Promise<T>[] attr;` work.

- README.md
- lib/webidl2.js
- package.json
- test/syntax/idl/extended-attributes.widl
- test/syntax/json/extended-attributes.json
This adds support for constructs of the form:
```
[Exposed=(Window,Worker)]
```
which were kind of supported, but not documented.
The proposed JSON syntax for the above would be:
```json
{
"name": "Exposed",
"arguments": null,
"rhs": {
"type": "identifier-list",
"value": [
"Global",
"Worker"
]
}
}
```
This introduces a new Right Hand Side type, the [identifier list](http://heycam.github.io/webidl/#prod-ExtendedAttributeIdentList). I'm happy to change the JSON syntax, though, if so, please LMK.
Note that currently, the above would be rendered as:
```json
{
"name": "Exposed",
"arguments": null,
"rhs": [
"Global",
"Worker"
]
}
```
> Add support for extended attributes identifier lists

- lib/webidl2.js
- test/syntax/idl/enum.widl
- test/syntax/json/enum.json
See https://github.com/heycam/webidl/commit/291dcc397f48029ac3954b2b0e511f4c14c7631d
> Allow trailing comma in enum value lists, per spec

- README.md
- lib/webidl2.js
- test/invalid/idl/typedef-nested.widl
- test/invalid/json/typedef-nested.json
- test/syntax.js
- test/syntax/idl/typedef-nested.widl
- test/syntax/json/typedef-nested.json
- test/syntax/opt/typedef-nested.json
The [official WebGL spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl) contains a few of these:
```WebIDL
interface WebGL2RenderingContextBase
{
//... 
typedef (Uint32Array or sequence<GLuint>) UniformUIVSource;
//... 
}
```
As far as I can tell, this is technically invalid Web IDL. However, I would like to be able to consume the official WebGL spec with no changes... Hence this PR.
I've added the following proposed usage of `parse()`:
```javascript
parse(..., {allowNestedTypedefs: true}) // Accept typedefs as valid members of interfaces
parse(...) // Works like before
```
Tests for both cases are included. Tangentially, there's also the infrastructure to configure the parser on a per-testcase basis, using JSON option files under `test/syntax/opt`, [like I did for …
> Allow typedefs within interfaces (behind an opt-in flag)

- lib/webidl2.js
- test/syntax/idl/extended-attributes.widl
- test/syntax/json/extended-attributes.json
This allows things like:
[Id=0] interface Foo {};
The spec (http://www.w3.org/TR/WebIDL/#idl-extended-attributes) isn't super clear on whether this should be allowed or not. I believe that it is saying that extended attributes have very permissive grammar in general, but the specific extended attributes discussed in the spec have specific restrictions.
> Accept wider (but still incomplete) set of allowed syntax for extended attributes

- package.json
- test/invalid.js
- test/syntax.js
- test/web/make-web-tests.js
- test/web/run-tests.js
expect.js does not exist under node_modules/expect.js, where
test/web/make-web-test.js wrongly referenced. Besides, the expect.js
project (https://www.npmjs.com/package/expect.js) is not actively
maintained, expect (https://www.npmjs.com/package/expect) is an good
alternative library to be used.
> Replace expect.js with expct

- lib/webidl2.js
`{"default": undefined}` in this 3 file.
```
test/syntax/idl/dictionary-inherits.widl
test/syntax/idl/dictionary.widl
test/syntax/idl/overloading.widl
```
tried this assertion in the `test/syntax.js`.
```js
assert.deepEqual(wp.parse(fs.readFileSync(idl, "utf8"), opt), JSON.parse(fs.readFileSync(json, "utf8")));
```
> Fix "default": undefined

- lib/webidl2.js
- test/syntax/idl/namespace.widl
- test/syntax/json/namespace.json
Fixes #51. Specifically this adds `namespace`, `noninherited_attribute` and `nonspecial_operation` functions to match the namespace syntax.
> Support namespaces

- lib/webidl2.js
- test/syntax/idl/extended-attributes.widl
- test/syntax/json/extended-attributes.json
```WebIDL
[
Constructor,
Constructor(double radius)
] // Currently errors here because the parser does not consume whitespaces before consuming bracket
interface Circle {
attribute double r;
attribute double cx;
attribute double cy;
readonly attribute double circumference;
};
```
> Fix whitespace error on parsing extended attributes

- .travis.yml
- package.json
1. Add Node LTS and stable branches to CI
2. Remove unused dependencies (specifically `microtime` fails to build on Node 7 with unknown reason)
> Test for latest LTS/stable node versions

- lib/webidl2.js
- test/invalid/idl/promise-with-extended-attribute.widl
- test/invalid/idl/record-key-with-extended-attribute.widl
- test/invalid/json/promise-with-extended-attribute.json
- test/invalid/json/record-key-with-extended-attribute.json
- test/syntax/idl/iterable.widl
- test/syntax/idl/maplike.widl
- test/syntax/idl/record.widl
- test/syntax/idl/sequence.widl
- test/syntax/idl/setlike.widl
- test/syntax/json/iterable.json
- test/syntax/json/maplike.json
- test/syntax/json/record.json
- test/syntax/json/sequence.json
- test/syntax/json/setlike.json
... which includes `sequence`, `FrozenArray` and `record`. `Promise` is intentionally not supported because of [the spec](https://heycam.github.io/webidl/#idl-types):
```
PromiseType ::
Promise < ReturnType >
```
> Support TypeWithExtendedAttributes on generics

- README.md
When IDL Type syntax is parsed, its resulting AST object has a property called "sequence". This is declared in the README everywhere except the IDL Type section.
> Add "sequence" property to IDL Type AST definition

- lib/webidl2.js
- test/invalid/idl/duplicate.widl
- test/invalid/json/duplicate.json
- test/syntax/idl/equivalent-decl.widl
- test/syntax/idl/overloading.widl
- test/syntax/idl/stringifier.widl
- test/syntax/json/equivalent-decl.json
- test/syntax/json/overloading.json
- test/syntax/json/stringifier.json
> Check duplicated names

- .travis.yml
- lib/webidl2.js
- package-lock.json
- package.json
- test/invalid.js
This is related to #82 but not really breaking compat with Node.js 4.
This PR converts:
* `var func = function() { }` style to `function func() { }`
* `var x` to `let x` or `const x` depending on the variable is reassigned or not
* ES5-style class declaration for WebIDLParseError to ES2015 one
* `for (var i = 0; i < array.length; i++)` to `for (const item of array)`
* callback functions to use arrow syntax
* object literal member functions `{ func: function () { } }` to `{ func() { } }`
PS: Now fixes #82 by removing it on `.travis.yml`.
> BREAKING CHANGE: Use ES2015 syntax

- README.md
- lib/webidl2.js
- test/syntax/json/enum.json
* closes #86 
This changes the return type of parsed `emum.values` from strings to objects. The Objects have two members, `type` and `value`: `{type: "string", value: "value" }`.
> BREAKING CHANGE: ret enum value as object

- test/invalid.js
- test/syntax.js
Looking at the tests I thought they should be rewritten in ES2015 before any possible fix here.
Additionally this removes lib-cov references that don't exist.
> Use ES2015 syntax for tests

- lib/webidl2.js
- test/invalid/idl/maplike-1type.widl
- test/invalid/idl/readonly-iterable.widl
- test/invalid/idl/setlike-2types.widl
- test/invalid/idl/typedef-nested.widl
- test/syntax/idl/extended-attributes.widl
- test/syntax/idl/identifier-qualified-names.widl
- test/syntax/idl/iterable.widl
- test/syntax/idl/legacyiterable.widl
- test/syntax/idl/maplike.widl
- test/syntax/idl/primitives.widl
- test/syntax/idl/setlike.widl
- test/syntax/json/sequence.json
See https://github.com/w3c/web-platform-tests/pull/8027. With these
changes, most of wpt's lints would pass for webidl2.js.
> Normalize some whitespace to pass wpt's lint

- .travis.yml
Follow latest stable and LTS going forward.
> chore: drop Node 6 support

- README.md
- lib/webidl2.js
- test/syntax/idl/mixin.widl
- test/syntax/json/mixin.json
(This includes #103)
Fixes #92.
[MixinMember](https://heycam.github.io/webidl/#prod-MixinMember) only includes stringifiers but not static members, while current `operation()`/`attribute()` always include both. This PR pulls `static_member()` and `stringifier()` out of `operation()`/`attribute()` to support mixins + better match the parser structure to the spec.
```
MixinMember ::
Const
RegularOperation
Stringifier
ReadOnly AttributeRest
```
Bonus: This renames nonspecial_operation to regular_operation to match the spec naming.
> Support mixins + includes statements

- lib/webidl2.js
- test/syntax/json/allowany.json
- test/syntax/json/constructor.json
- test/syntax/json/extended-attributes.json
- test/syntax/json/iterable.json
- test/syntax/json/maplike.json
- test/syntax/json/nointerfaceobject.json
- test/syntax/json/overloading.json
- test/syntax/json/overridebuiltins.json
- test/syntax/json/prototyperoot.json
- test/syntax/json/record.json
- test/syntax/json/replaceable.json
- test/syntax/json/sequence.json
- test/syntax/json/setlike.json
- test/syntax/json/stringifier-attribute.json
- test/syntax/json/stringifier-custom.json
- test/syntax/json/typedef.json
- test/syntax/json/uniontype.json
> Always add rhs property

- .travis.yml
- package-lock.json
- package.json
Per https://github.com/w3c/webidl2.js/pull/102#issuecomment-343852600. Also some metadata updates.
>  Revert "chore: drop Node 6 support (#102)"

- lib/webidl2.js
- test/syntax/json/iterable.json
- test/syntax/json/legacyiterable.json
- test/syntax/json/setlike.json
This removes pain when processing `iterable` and its friends with different member counts. See #113
> Consistent array type for iterable.idlType

- test/invalid.js
- test/syntax.js
Because I don't want to see those `i++`s 😁
Removed `idls.map` to do this.
> Use for-of on tests

- README.md
#61 removed `typeExtAttrs`, so this PR removes it from the documentation.
> Remove typeExtAttrs from docs

- lib/webidl2.js
- test/invalid/idl/no-semicolon-callback.widl
- test/invalid/idl/no-semicolon.widl
- test/invalid/json/array.json
- test/invalid/json/caller.json
- test/invalid/json/dict-required-default.json
- test/invalid/json/duplicate.json
- test/invalid/json/enum.json
- test/invalid/json/exception.json
- test/invalid/json/iterator.json
- test/invalid/json/maplike-1type.json
- test/invalid/json/module.json
- test/invalid/json/no-semicolon-callback.json
- test/invalid/json/no-semicolon.json
- test/invalid/json/nonnullableany.json
- test/invalid/json/nonnullableobjects.json
- test/invalid/json/promise-with-extended-attribute.json
- test/invalid/json/raises.json
- test/invalid/json/readonly-iterable.json
- test/invalid/json/record-key-with-extended-attribute.json
- test/invalid/json/record-key.json
- test/invalid/json/scopedname.json
- test/invalid/json/sequenceAsAttribute.json
- test/invalid/json/setlike-2types.json
- test/invalid/json/setter-creator.json
- test/invalid/json/special-omittable.json
- test/invalid/json/stringconstants.json
- test/invalid/json/typedef-nested.json
Fixes #119 
This should be simple enough 😁
> Let error messages include the current definition name

- lib/webidl2.js
- test/syntax/json/constants.json
- test/syntax/json/nullable.json
Now for `const-type`.
I'm not very happy with a field `idlType` again have its own `idlType`, can we rename it so that we can reduce same names?
> feat: add const-type for idlTypes 

- lib/webidl2.js
- test/syntax/json/extended-attributes.json
- test/syntax/json/record.json
- test/syntax/json/typedef-union.json
- test/syntax/json/uniontype.json
I think this will better fit for #93, as otherwise we have to go one level deeper to get the type of a union type. What do you think?
> Type on union idlType

- lib/webidl2.js
- lib/writer.js
- test/util/collect.js
Keywords can be used as property names in ES5 so this PR removes quotes for them.
Originally I intended to use `array.join()` for string concatenation in writer.js and then found that [it's actually slower on V8](http://jsben.ch/ltdI2). Hmm.
```diff
function iterate(things) {
if (!things) return;
-  let ret = "";
-  for (const thing of things) ret += dispatch(thing);
-  return ret;
+  return things.map(dispatch).join('');
};
> refactor: small syntax changes

- lib/webidl2.js
- test/invalid/idl/stray-slash.widl
- test/invalid/json/stray-slash.json
Tokenisation and whitespace skipping are two major hot spots for the parser.
Optimise by:
1. Using re.exec() instead of str.replace()
2. Using re.lastIndex with sticky expressions to avoid repeatedly trimming the front of the string
3. Using str.indexOf('\n') when counting newlines
5. Using a zero-width lookahead to quickly reject integers in the "float" regexp
6. Tweaking other regexps
7. Peeking at the next character in tokenise() to reduce the number of regular expressions that need to be checked at each position
8. Moving initialisation of re tables out of the hot path
Also optimise the removal of quotation marks from strings by using str.substring() instead of str.replace().
Due to optimisation of the "whitespace" regexp tokenise() now splits "  // foo" into two tokens ("  " and "// …
> Optimise tokenisation and whitespace skipping

- README.md
#93 adds `type` for IDL type structure, so this PR adds documentations for that.
It currently can be `null` in generic and union types.
> docs(README): add types of types [ci skip]

- README.md
- lib/webidl2.js
- test/syntax/json/constants.json
- test/syntax/json/nullable.json
#141 didn't cover `const-type` so this PR adds full IDL type members to it. Those will always have the same values but it's better than forcing existence check.
> const-type as full IDL Type

- lib/webidl2.js
This removes the need for the third argument `re`.
> refactor: one-to-one match for token matcher

- lib/webidl2.js
> refactor: remove eas.length check

- lib/webidl2.js
- test/invalid/idl/implements_and_includes_ws.widl
- test/invalid/json/implements_and_includes_ws.json
The all_ws() production here might return undefined for certain badly
formed WebIDL (for example, the simple text "foobar;"). Be careful not
to unshift an undefined value onto the tokens array.
> Fix whitespace handling of implements and includes.

- lib/webidl2.js
- test/invalid/idl/extattr-empty-ids.widl
- test/invalid/json/extattr-empty-ids.json
This PR:
1. avoids checking `(` twice in different if-branches
2. removes old MapClass related variable and comment
3. throws if an identifier list is empty
> Refactor simple_extended_attr();

- lib/webidl2.js
...to better align with [the spec](https://heycam.github.io/webidl/#idl-grammar):
>Implicitly, any number of whitespace and comment terminals are allowed between every other terminal in the input text being parsed.
Now:
1. We don't have to manually add `all_ws()` everywhere (so that we can prevent bugs like #68).
2. All trivia tokens are stored, no need to manually process it when rollback (to prevent bugs like #145).
3. The stored trivia tokens help implementing #125 😁
> Remove all_ws() and gather trivia implicitly

- lib/webidl2.js
- test/invalid/json/id-underscored-number.json
It turns out I was not fully understanding the tokenizer error. The `other` regex was different from the one in the spec and it was causing token stream error. Now `_0` is parsed as: `_` as `other` and `0` as `integer`.
> fix: prevent tokeniser error when it meets _0

- lib/webidl2.js
- test/invalid/idl/union-dangling-or.widl
- test/invalid/idl/union-one.widl
- test/invalid/idl/union-zero.widl
- test/invalid/json/union-dangling-or.json
- test/invalid/json/union-one.json
- test/invalid/json/union-zero.json
https://heycam.github.io/webidl/#prod-UnionType
```
UnionType ::
( UnionMemberType or UnionMemberType UnionMemberTypes )
UnionMemberType ::
ExtendedAttributeList NonAnyType
UnionType Null
UnionMemberTypes ::
or UnionMemberType UnionMemberTypes
ε
```
```webidl
typedef (OnlyOne) UnionOne; // shouldn't pass, at least two types are required inside a union
```
Also it turns out we don't have any tests for incorrect union types so I added some.
> fix: prevent incorrect union types

- lib/webidl2.js
- test/invalid/idl/namespace-readwrite.widl
- test/invalid/json/namespace-readwrite.json
https://heycam.github.io/webidl/#index-prod-NamespaceMember
```
NamespaceMember ::
RegularOperation
readonly AttributeRest
```
A namespace attribute must be readonly, but currently readwrite attributes are allowed. This PR fixes it.
> fix: prevent readwrite attributes on namespaces 

- lib/writer.js
- test/syntax/idl/inherits-getter.widl
- test/syntax/json/inherits-getter.json
https://heycam.github.io/webidl/#prod-ReadWriteAttribute
```
ReadWriteAttribute ::
inherit ReadOnly AttributeRest
AttributeRest
```
`inherit readonly`, not `readonly inherit` 😁
This only affects the currently unexposed writer so IMO no need for a version bump.
> fix: write inherit readonly attribute in proper order

- lib/webidl2.js
- test/syntax/idl/identifier-qualified-names.widl
- test/syntax/json/identifier-qualified-names.json
https://heycam.github.io/webidl/#index-prod-ArgumentNameKeyword
>Operation arguments can take a slightly wider set of identifiers. In an operation declaration, the identifier of an argument is specified immediately after its type and is given by either an identifier token or by one of the keywords that match the ArgumentNameKeyword symbol. If one of these keywords is used, it need not be escaped with a leading underscore.
Closes #169. This was a regression from #157.
> fix: allow selected keywords in argument name

- lib/webidl2.js
I tried modifying `operation()` to fix something and then found I have to modify both operation functions. This PR merges them so we can have a single operation function.
> refactor: merge operation functions

- lib/webidl2.js
- test/invalid/idl/nonnullableobjects.widl
- test/invalid/json/nonnullableobjects.json
This PR introduces `probe()` function which checks whether the next unconsumed token has the target type.
Currently checking excessive tokens requires using `consume()`:
```js
if (consume("?")) error("Can't nullable more than once");
```
Our `error()` method assumes that the error is from the first unconsumed token so it potentially throws with incorrect line number. The error message from the following example says it's from line 3 because the first unconsumed token is there.
```webidl
interface X {
attribute object?? // error is from line 2, but webidl2.js throws with line 3
attributeName;
};
```
`probe()` will fix this by checking the next token without consuming it:
```js
if (probe("?")) error("Can't nullable more than once");
```
> Add probe() function

- lib/webidl2.js
- test/invalid/idl/promise-nullable.widl
- test/invalid/idl/record-single.widl
- test/invalid/idl/unknown-generic.widl
- test/invalid/json/promise-nullable.json
- test/invalid/json/readonly-iterable.json
- test/invalid/json/record-key.json
- test/invalid/json/record-single.json
- test/invalid/json/stringconstants.json
- test/invalid/json/typedef-nested.json
- test/invalid/json/unknown-generic.json
- test/syntax/idl/generic.widl
- test/syntax/idl/promise-void.widl
- test/syntax/idl/record.widl
- test/syntax/idl/sequence.widl
- test/syntax/json/generic.json
- test/syntax/json/promise-void.json
- test/syntax/json/record.json
- test/syntax/json/sequence.json
This PR:
1. fixes #168 
2. fixes a bug where `Promise<void>?` was allowed (See https://heycam.github.io/webidl/#prod-NonAnyType)
1. adds generic/string type terminals as keywords
2. splits generic type parser into a new function `generic()`.
3. `return_type()` now does not throw, instead the callers should manage errors  with proper messages
> fix: consume return type for promise subtype

- lib/webidl2.js
- test/syntax/json/allowany.json
- test/syntax/json/callback.json
- test/syntax/json/constructor.json
- test/syntax/json/enum.json
- test/syntax/json/equivalent-decl.json
- test/syntax/json/extended-attributes.json
- test/syntax/json/getter-setter.json
- test/syntax/json/identifier-qualified-names.json
- test/syntax/json/implements.json
- test/syntax/json/indexed-properties.json
- test/syntax/json/namedconstructor.json
- test/syntax/json/namespace.json
- test/syntax/json/nointerfaceobject.json
- test/syntax/json/nullableobjects.json
- test/syntax/json/operation-optional-arg.json
- test/syntax/json/overloading.json
- test/syntax/json/overridebuiltins.json
- test/syntax/json/record.json
- test/syntax/json/reg-operations.json
- test/syntax/json/sequence.json
- test/syntax/json/static.json
- test/syntax/json/treatasnull.json
- test/syntax/json/treatasundefined.json
- test/syntax/json/typedef.json
- test/syntax/json/typesuffixes.json
- test/syntax/json/variadic-operations.json
This PR:
1. removes use of `array.unshift()` 😁
2. removes any need to remember all tokens to unconsume, prevents bugs like #145 
3. enables, but not in this PR, potentially better error message by showing preceding tokens in situations like #178. Not sure how should the format be.
4. fixes strange token order in error messages:
```
> require(".").parse("interface X { operation(optional sequence<abc>); }");
Thrown: Got an error during or right after parsing `interface X`: Unterminated operation, line 1 (tokens: ">optional); }")
```
5. always add `default` field for arguments. Previously it was added only when the value exists.
> refactor: unconsume by position

- lib/webidl2.js
- lib/writer.js
Thanks to variadic `consume()` by #173. Also removes some remaining ES3-era property accesses.
> refactor: consume argument name in object spread way

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/dictionary-inherits.json
- test/syntax/json/dictionary.json
IMO `map()`+`join()` is better for readability than a for i++ loop 😁
Also removes obsolete `creator` and `legacycaller` from writer.
> refactor(lib/writer): remove args()

- lib/webidl2.js
- test/invalid/idl/iterable-empty.widl
- test/invalid/json/iterable-empty.json
```webidl
interface X {
iterable<>; // should be illegal
};
```
Fixes a mistake. 🤣
> fix: prevent empty iterable declaration

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/constants.json
- test/syntax/json/nullable.json
It's weird that `cnt.nullable` is `true` and then `cnt.idlType.nullable` is `false`.
Actually more weird thing is that the const type is allowed to be nullable (https://github.com/heycam/webidl/issues/448).
Also some refactorings in writer.js.
> BREAKING CHANGE: move nullable field from const type to .idlType

- lib/webidl2.js
- lib/writer.js
- test/syntax/json/iterable.json
- test/syntax/json/legacyiterable.json
- test/syntax/json/maplike.json
- test/syntax/json/setlike.json
Again includes a null pattern for optional `readonly`.
> Add trivia for iterable declarations

- .eslintrc.json
- lib/webidl2.js
- lib/writer.js
- package-lock.json
- package.json
- test/invalid.js
- test/syntax.js
- test/writer.js
Same code changes, but with a minimal configuration.
> Use eslint minimally

- README.md
- lib/webidl2.js
- lib/writer.js
- test/syntax/json/iterable.json
- test/syntax/json/legacyiterable.json
- test/syntax/json/maplike.json
- test/syntax/json/setlike.json
Also including renaming from `trivia.type` to `trivia.base` for consistency with other types.
> Document trivia for iterable-likes

- README.md
A stringifier may miss a body, but the body always includes idlType.
> chore(README): operation body always has idlType

- lib/writer.js
Currently writer.js tends to be horizontally loooong, so this PR makes it shorter for `type()`.
Also named variables will probably help future refactoring.
We may ultimately enable [eslint max-len rule](https://eslint.org/docs/rules/max-len).
> refactor(lib/writer): horizontally shorter type()

- lib/writer.js
Removing them enables shorter code 😎 and eases further refactoring 👍
> refactor(lib/writer): reduce conditional constructs

- lib/writer.js
`namespace()` and `dictionary()` are so much like `interface_()` so this PR removes them.
> refactor(lib/writer): use interface_like()

- lib/writer.js
- test/syntax/idl/attributes.widl
- test/syntax/json/attributes.json
This introduces a way to customize the output of `write()` so that tools e.g. ReSpec can add HTML tags on it. Basically what was described in https://github.com/w3c/webidl2.js/issues/210#issuecomment-400552326.
Should only be merged after [the respec side of PR](https://github.com/w3c/respec/pull/1920) gets approved, so that we can make sure that this covers everything ReSpec requires.
TODO:
> [WIP] write() with optional templates

- lib/webidl2.js
- test/syntax/baseline/allowany.json
- test/syntax/baseline/callback.json
- test/syntax/baseline/constructor.json
- test/syntax/baseline/enum.json
- test/syntax/baseline/equivalent-decl.json
- test/syntax/baseline/extended-attributes.json
- test/syntax/baseline/getter-setter.json
- test/syntax/baseline/identifier-qualified-names.json
- test/syntax/baseline/indexed-properties.json
- test/syntax/baseline/namedconstructor.json
- test/syntax/baseline/namespace.json
- test/syntax/baseline/nointerfaceobject.json
- test/syntax/baseline/nullableobjects.json
- test/syntax/baseline/operation-optional-arg.json
- test/syntax/baseline/overloading.json
- test/syntax/baseline/overridebuiltins.json
- test/syntax/baseline/record.json
- test/syntax/baseline/reg-operations.json
- test/syntax/baseline/sequence.json
- test/syntax/baseline/static.json
- test/syntax/baseline/treatasnull.json
- test/syntax/baseline/treatasundefined.json
- test/syntax/baseline/typedef.json
- test/syntax/baseline/typesuffixes.json
- test/syntax/baseline/variadic-operations.json
Fixes #246 
Previously the following example added information for `[TreatNullAs=EmptyString]` to argument objects, now it goes to IDL types as it does in attributes.
```webidl
[Exposed=Window]
interface Dog {
attribute DOMString name;
attribute [TreatNullAs=EmptyString] DOMString owner;
boolean isMemberOfBreed([TreatNullAs=EmptyString] DOMString breedName);
};
```
> BREAKING CHANGE: remove .extAttrs from arguments

- README.md
If based on a real namespace, might as well match the name:
https://console.spec.whatwg.org/#console-namespace
> Lowercase the example namespace "Console"

- lib/webidl2.js
- test/invalid/baseline/enum-wo-comma.txt
Modifying token object causes side effect 😄
> fix(lib/webidl2): restore enum value string form in error

- checker/index.html
[It was a Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=705478) that `innerText` inserted newlines to textarea. Now `innerText` does not add newlines so we should use `textContent` instead.
> fix(checker): avoid using innerText

- lib/webidl2.js
- test/syntax/baseline/identifier-hyphen.json
- test/syntax/idl/identifier-hyphen.widl
Following https://github.com/heycam/webidl/pull/633.
> fix(lib/webidl2): allow a preceding hyphen for identifiers

- lib/webidl2.js
- lib/writer.js
- test/syntax/baseline/dictionary-inherits.json
- test/syntax/baseline/dictionary.json
- test/writer.js
Removes a redundant argument from `name_token()`.
> refactor: dictionary as a class

- test/invalid/baseline/extattr-double.txt
- test/invalid/idl/extattr-double.widl
#248 fixed the issue but not added a test case.
Closes #191
> test(lib/webidl2): case for double extended attributes in arguments

- lib/webidl2.js
- lib/writer.js
- test/writer.js
This removes `valueLiteral` writer hook because it turns out that ReSpec doesn't need it.
> BREAKING CHANGE: constant as a class

- lib/webidl2.js
- test/invalid/baseline/const-null.txt
- test/invalid/baseline/const-nullable.txt
- test/invalid/idl/const-null.widl
- test/invalid/idl/const-nullable.widl
- test/syntax/baseline/nullable.json
- test/syntax/idl/nullable.widl
Following https://github.com/heycam/webidl/pull/686.
> fix(lib/webidl2): disallow null on constants

- checker/index.html
- index.js
- lib/validator.js
- lib/webidl2.js
- lib/writer.js
- package.json
- webpack.config.js
Because modules everywhere 😄
Also replacing default export with named exports, which will allow `import { parse } from "webidl2"`.
> refactor: use module for checker

- lib/helpers.js
- lib/productions/helpers.js
- lib/productions/includes.js
- lib/productions/token.js
- lib/tokeniser.js
- lib/webidl2.js
Harder to modularize things than I thought because `ExtendedAttributes` depends on `argument_list()` which depends on `Argument` which again depends on `ExtendedAttributes` and `Type`...
> refactor: modularize Token and list()

- lib/writer.js
- test/writer.js
Previously `Promise`, `sequence`, etc. were hooked by `reference()` but `generic()` will do it instead in this PR.
> BREAKING CHANGE: introduce `generic()` writer hook

- lib/productions/default.js
- lib/productions/includes.js
- lib/productions/token.js
- lib/tokeniser.js
- lib/webidl2.js
- test/invalid/baseline/dict-no-default.txt
- test/invalid/idl/dict-no-default.widl
The error message was incorrectly passed and thus caused things be undefined.
Caught in https://github.com/w3c/webidl2.js/issues/316#issuecomment-488042536, thanks @bglgwyng!
> fix(lib/webidl2): emit error message correctly

- README.md
> docs(lib/webidl2): represent `extAttrs` as an array

- README.md
Requested from #327. Not introducing an option yet.
> docs(lib/webidl2): document `eof`

- lib/webidl2.js
- test/invalid/baseline/inherit-readonly.txt
- test/invalid/idl/inherit-readonly.widl
- test/syntax/baseline/inherits-getter.json
- test/syntax/idl/inherits-getter.widl
Follows https://github.com/heycam/webidl/pull/704, but it has been already invalid.
> fix(lib/webidl2): inherited attributes cannot be readonly

- README.md
- lib/webidl2.js
- test/syntax.js
- test/util/acquire.js
- test/util/collect.js
- test/writer.js
More straightforward for non-ReSpec use that does not rely on `.write()`.
Closes #327
> BREAKING CHANGE: emit eof only if options.concrete=true

- lib/productions/callback.js
- lib/productions/iterable.js
- lib/webidl2.js
- test/invalid/baseline/callback-noassign.txt
- test/invalid/baseline/callback-noparen.txt
- test/invalid/baseline/callback-noreturn.txt
- test/invalid/baseline/callback-semicolon.txt
- test/invalid/baseline/iterable-empty.txt
- test/invalid/baseline/iterable-notype.txt
- test/invalid/baseline/setlike-2types.txt
- test/invalid/idl/callback-noassign.widl
- test/invalid/idl/callback-noparen.widl
- test/invalid/idl/callback-noreturn.widl
- test/invalid/idl/callback-semicolon.widl
- test/invalid/idl/iterable-notype.widl
One more PR is left and I think the next one is about validating #338.
> refactor(lib/webidl2): modularize callback+iterable

- lib/productions/callback-interface.js
- lib/productions/interface.js
- lib/webidl2.js
- test/invalid/baseline/callback-attribute.txt
- test/invalid/baseline/no-semicolon-callback.txt
- test/invalid/idl/callback-attribute.widl
- test/invalid/idl/no-semicolon-callback.widl
From https://github.com/heycam/webidl/pull/705.
~~(Oops, this was to be a draft. Why doesn't GitHub allow changing a normal PR to a draft 🤔)~~
Now ready to be reviewed 🎉
> fix(callback-interface): apply member type restriction 

- lib/productions/container.js
- lib/productions/operation.js
- lib/validator.js
- lib/validators/helper.js
- test/invalid/baseline/operation-dict-default.txt
- test/invalid/idl/operation-dict-default.widl
So this is for ReSpec and WPT to match the new spec change (#338). We still need a way to insert xref data into validator, but that can probably be done in ReSpec without webidl2 changes.
> feat(productions/operation): require default value for dictionary arguments

- package.json
Because building our library shouldn't require webpack knowledge.
> chore(package): add build commands

- lib/productions/interface.js
- lib/validator.js
- lib/validators/interface.js
Also fixed a problem where mixin map is constructed repeatedly for every interface.
> refactor(lib/validator): modularize checkInterfaceMemberDuplication

- lib/error.js
- test/invalid.js
Because emitting strings prevents programmatically track the right files, and potentially also prevents advanced features like tracking the problematic line instead of the whole IDL block.
> BREAKING CHANGE: emit validation objects

- lib/error.js
- lib/productions/interface.js
- lib/tokeniser.js
- test/invalid.js
- test/invalid/baseline/exposed.txt
- test/util/acquire.js
Splitting code context and error message will ease tools to format them user friendly, e.g. by wrapping `context` with `<pre>` and treating `bareMessage` as markdown.
>  feat(lib/error): add .bareMessage and .context 

- lib/productions/interface.js
- test/invalid/baseline/exposed.txt
- test/invalid/idl/exposed.webidl
My understanding is NoInterfaceObject will be removed soon (https://github.com/heycam/webidl/pull/609) but that didn't happen yet.
Closes #370.
> fix: suppress Exposed requirement when NoInterfaceObject

- lib/productions/callback.js
Brave Browser was giving me 404s and not loading the files at load because it didn't automatically add the JS file extension to imports, so I added `.js` to both of the imports.
> Add file extensions

- lib/productions/attribute.js
- lib/productions/operation.js
- lib/tokeniser.js
- test/syntax/baseline/async-name.json
- test/syntax/baseline/includes-name.json
- test/syntax/idl/async-name.webidl
- test/syntax/idl/includes-name.webidl
Corresponds to https://github.com/heycam/webidl/pull/769.
> Allow `async` and `includes` as member names

- .github/workflows/nodejs.yml
> Setup GitHub Actions

- lib/productions/argument.js
- test/invalid/baseline/argument-dict-nullable.txt
- test/invalid/idl/argument-dict-nullable.webidl
Currently the validator suggests adding a default dictionary value for a dictionary argument even it's nullable, but it's not a valid suggestion because a nullable dictionary type is not really a dictionary type. (https://github.com/heycam/webidl/issues/774#issuecomment-524229029)
> fix(productions/argument): no default for nullable dictionary args

- lib/productions/argument.js
- lib/validators/helpers.js
- test/invalid/baseline/nullable-union-dictionary.txt
- test/invalid/idl/nullable-union-dictionary.webidl
To align better with [the spec](https://heycam.github.io/webidl/#idl-nullable-type).
> fix(validators): treat only non-nullables

- lib/tokeniser.js
- test/invalid/baseline/tostring.txt
- test/invalid/idl/tostring.webidl
Closes #230.
I think throwing early on tokenising phase is easiest and best.
> fix(tokeniser): prevent any use of toString

- README.md
- lib/writer.js
- test/writer.js
Not sure this is best, but it at least provide a way to link constructors and stringifiers (required in https://github.com/w3c/respec/issues/982)
> feat(lib/writer): add hook for nameless members

- lib/tokeniser.js
- test/invalid/baseline/constructor-escaped.txt
- test/invalid/baseline/tostring-escaped.txt
- test/invalid/idl/constructor-escaped.webidl
- test/invalid/idl/tostring-escaped.webidl
Because [the spec says](https://heycam.github.io/webidl/#idl-names):
>For all of these constructs, the identifier is the value of the identifier token with any leading U+005F LOW LINE ("_") character (underscore) removed.
>The identifier of any of the abovementioned IDL constructs must not be "constructor", "toString", or begin with a U+005F LOW LINE ("_") character. These are known as reserved identifiers.
> fix(tokeniser): prevent escaping reserved identifiers

- lib/productions/operation.js
- test/invalid/baseline/operation-nameless.txt
- test/invalid/idl/operation-nameless.webidl
[The syntax](https://heycam.github.io/webidl/#prod-OperationRest) somehow allows this, so this patch only warns when if no identifier [per the prose](https://heycam.github.io/webidl/#idl-operations):
>If an operation has no identifier, then it must be declared to be a special operation using one of the special keywords.
> fix(productions/operation): warn if no operation identifier

- lib/productions/helpers.js
- lib/productions/interface.js
- test/autofix.js
Because... It seems this is what people do, https://github.com/heycam/webidl/pull/780 and https://github.com/w3c/speech-api/pull/63 for example.
> fix(productions/interface): put constructor on the top position

- lib/productions/interface.js
- test/autofix.js
Currently
```
[Constructor(),
Exposed=Window]
```
Becomes:
```
[
Exposed=Window]
```
and this patch generates simple `[Exposed=Window]` instead.
> fix(productions/interface): whitespace cleanup after autofix

- lib/productions/helpers.js
- lib/productions/interface.js
- test/autofix.js
There was a bug that `constructor()` get too much indentation or too less.
> fix(productions/interface): correct constructor indentation

- lib/productions/helpers.js
- lib/productions/interface.js
- test/autofix.js
Because people are using 4 spaces, 3 spaces, 1 space or even `\t`.
> fix(autofix): support arbitrary indentation

- lib/productions/interface.js
- test/autofix.js
Because simple `unshift()` causes reversed order 😄
> fix(autofix): correct constructor ordering

- lib/productions/helpers.js
- test/autofix.js
Because operations does not have keywords in front of them.
> fix(autofix): properly detect operation indentation

- lib/productions/extended-attributes.js
- lib/productions/token.js
- test/syntax/baseline/extended-attributes.json
- test/syntax/idl/extended-attributes.webidl
A regression found in https://github.com/jsdom/webidl2js/pull/138. cc: @domenic
> fix(productions/extended-attributes): unescape identifier values

- lib/productions/constant.js
- test/syntax/baseline/constants.json
- test/syntax/idl/constants.webidl
Quickfix for https://github.com/jsdom/webidl2js/pull/138#issuecomment-541604206. Thanks for finding bugs, @domenic 👍
> fix(productions/constant): unescape name

- package.json
This reverts commit 286942bad1afdbcc0aab1b54294174e8c688e11f.
This solves the failure in #457. [Per the document](https://nodejs.org/api/esm.html#esm_ecmascript_modules) it's still experimental (although [it's recommended](https://medium.com/@nodejs/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663)) and it conflicts with webpack.
> Revert "chore(package): add type field (#450)"

- README.md
- lib/productions/extended-attributes.js
- lib/writer.js
- test/invalid/baseline/extattr-empty-ids.txt
- test/syntax/baseline/extended-attributes.json
- test/syntax/baseline/reflector-interface.json
- test/syntax/idl/extended-attributes.webidl
- test/syntax/idl/reflector-interface.webidl
This better conforms with the permissiveness of extended attributes.
This patch closes #455 and includes:
> feat(extended-attributes): support decimals/integers

- README.md
- lib/productions/iterable.js
- test/invalid/baseline/async-iterable-single.txt
- test/invalid/idl/async-iterable-single.webidl
- test/syntax/baseline/async-iterable.json
- test/syntax/idl/async-iterable.webidl
This patch implements async value iterable for #464 and includes:
> feat(productions/iterable): support async value iterable

- package-lock.json
- package.json
This PR also updates package-lock.json to use latest dependency chain as much as possible.
> chore(package): update deps

- README.md
- lib/productions/iterable.js
- lib/writer.js
- test/invalid/baseline/argument-dict-default.txt
- test/invalid/baseline/argument-dict-nullable.txt
- test/invalid/baseline/argument-dict-optional.txt
- test/invalid/baseline/async-iterable-unterminated-args.txt
- test/invalid/baseline/iterable-args.txt
- test/invalid/baseline/maplike-args.txt
- test/invalid/baseline/setlike-args.txt
- test/invalid/idl/argument-dict-default.webidl
- test/invalid/idl/argument-dict-nullable.webidl
- test/invalid/idl/argument-dict-optional.webidl
- test/invalid/idl/async-iterable-unterminated-args.webidl
- test/invalid/idl/iterable-args.webidl
- test/invalid/idl/maplike-args.webidl
- test/invalid/idl/setlike-args.webidl
- test/syntax/baseline/async-iterable.json
- test/syntax/baseline/iterable.json
- test/syntax/baseline/maplike.json
- test/syntax/baseline/setlike.json
- test/syntax/idl/async-iterable.webidl
This patch closes #464 and includes:
> feat(productions/iterable): support async iterable arguments 

- README.md
Constant values of type boolean and sequence types are not stored as strings.
This patch closes #535 and includes:
> chore(README): Update documentation for constant values

- README.md
One part of the README still uses the old separate static,
stringifier, and inherit fields. In other places it is stated that the
special field is null in the default case, when in fact the special
field is set to the empty string.
This patch closes #533 and includes:
> chore(README): Update documentation for the `special` field

- README.md
This patch closes #531 and includes:
> chore(README): Document the `default` field of arguments

- lib/validators/helpers.js
- test/invalid/baseline/argument-dict-optional.txt
- test/invalid/idl/argument-dict-optional.webidl
The two `return true` statements would leave undefined in the cache, and
looking up the same dictionary again would then return undefined instead
of true. The bug manifests when the same dictionary appears as an
argument twice or more.
This patch closes https://github.com/w3c/webidl2.js/issues/545 and includes:
> Ensure cached values of dictionaryIncludesRequiredField are boolean

- .gitignore
- dist/package.json
- package.json
- test/commonjs.cjs
Okay, it turns out @exe-boss was right, and simple `exports` blocks CommonJS imports. I should have read https://github.com/w3c/webidl2.js/pull/556#discussion_r609879465 more carefully, especially https://nodejs.org/api/packages.html#packages_conditional_exports 😬
Somehow I thought Node would wrap ES modules to CommonJS as they do vise versa, but it doesn't.
> fix(package): allow require() for commonjs use

- lib/productions/argument.js
- lib/productions/attribute.js
- lib/productions/callback.js
- lib/productions/constant.js
- lib/productions/container.js
- lib/productions/default.js
- lib/productions/enum.js
- lib/productions/extended-attributes.js
- lib/productions/field.js
- lib/productions/helpers.js
- lib/productions/includes.js
- lib/productions/operation.js
- lib/productions/token.js
- lib/productions/type.js
- lib/productions/typedef.js
- lib/tokeniser.js
- lib/webidl2.js
This patch closes #313 and includes:
> refactor: split consume(regex) as consumeType()

- lib/productions/enum.js
- lib/productions/extended-attributes.js
- lib/productions/token.js
Currently the name conflicts with the name for raw tokens.
> refactor: rename Token to WrappedToken

- webpack.config.cjs
In ESM `this` is undefined at the top level. Instead to access the global object you must use `globalThis`.
This is causing some issues in Deno when running WPT idlharness tests, because all code is always executed in a module context.
> fix: change globalObject to `globalThis`

- lib/productions/extended-attributes.js
- test/writer.js
Should fix the error in https://github.com/w3c/respec/pull/3536.
> fix(productions/extended-attribute): pass correct parent object

- lib/tokeniser.js
- test/syntax.js
Regressed by #566. The spec is explicitly using Perl regex syntax where `.` also matches `\r` but that doesn't apply to JavaScript.
> fix(tokeniser): match CRLF inside a comment

- lib/productions/callback-interface.js
- lib/productions/container.js
- lib/productions/dictionary.js
- lib/productions/interface.js
- lib/productions/mixin.js
- lib/productions/namespace.js
> refactor(container): remove redundant type parameter

- lib/productions/argument.js
- lib/productions/attribute.js
- lib/productions/callback.js
- lib/productions/constant.js
- lib/productions/container.js
- lib/productions/default.js
- lib/productions/enum.js
- lib/productions/extended-attributes.js
- lib/productions/field.js
- lib/productions/helpers.js
- lib/productions/includes.js
- lib/productions/operation.js
- lib/productions/token.js
- lib/productions/type.js
- lib/productions/typedef.js
- lib/tokeniser.js
- lib/webidl2.js
"type" has a special meaning in Web IDL (idl type), so probably better to use "kind" rather than overloading the word.
> refactor: rename consumeType to consumeKind

- README.md
Currently, the `checker` link refers to the [`checker` folder](https://github.com/w3c/webidl2.js/tree/main/checker) in this repository but I wonder maybe the https://w3c.github.io/webidl2.js/checker/ online checker might be the right one.
> Fix online checker link

- lib/productions/extended-attributes.js
- test/invalid/baseline/extattr-empty.txt
- test/invalid/baseline/extattr-invalid-rhs.txt
- test/invalid/baseline/extattr-no-rhs.txt
- test/invalid/idl/extattr-empty.webidl
- test/invalid/idl/extattr-invalid-rhs.webidl
- test/invalid/idl/extattr-no-rhs.webidl
> Better errors for extended attributes

- checker/index.html
`.textContent` is ignored when the value is modified.
> fix(checker): use `.value` instead of `.textContent` for textareas

- lib/productions/attribute.js
- lib/validators/helpers.js
- test/invalid/baseline/invalid-attribute.txt
- test/invalid/idl/invalid-attribute.webidl
For WebGPU case.
This patch closes #739  and includes:
> feat(validator): no EnforceRange for readonly attributes

- docs/custom-productions.md
- lib/productions/index.js
- package.json
This does not expose top level productions for now, since the parse function of them have some weird internal-only behavior, e.g. `Interface.parse` does not parse `interface` keyword by itself. Technically same for `Attribute` and `Operation`, but they are usable at least.
> feat: expose non-top-level production classes

- .gitattributes
- README.md
- lib/productions/type.js
- lib/tokeniser.js
- test/autofix.js
- test/invalid/baseline/invalid-allowshared.txt
- test/invalid/baseline/sharedarraybuffer.txt
- test/invalid/idl/invalid-allowshared.webidl
- test/invalid/idl/sharedarraybuffer.webidl
- test/syntax/baseline/sharedarraybuffer.json
- test/syntax/idl/sharedarraybuffer.webidl
This patch closes #746 and includes:
> feat: parse SharedArrayBuffer and validate AllowShared

- lib/productions/type.js
- test/syntax/baseline/bigint.json
- test/syntax/baseline/constructor.json
- test/syntax/baseline/extended-attributes.json
- test/syntax/baseline/record.json
- test/syntax/baseline/typedef-union.json
- test/syntax/baseline/undefined.json
- test/syntax/baseline/uniontype.json
This patch closes https://github.com/w3c/webidl2.js/issues/751 and includes:
> fix: pass parent type recursively

- lib/tokeniser.js
- test/syntax/baseline/buffersource.json
- test/syntax/idl/buffersource.webidl
Adds support for Float16Array from the [Float16Array proposal for JS](https://github.com/tc39/proposal-float16array); corresponding webidl change at https://github.com/whatwg/webidl/pull/1398.
> feat: add Float16Array

- README.md
- lib/productions/iterable.js
- lib/tokeniser.js
- test/autofix.js
- test/invalid/baseline/argument-dict-default.txt
- test/invalid/baseline/argument-dict-nullable.txt
- test/invalid/baseline/argument-dict-optional.txt
- test/invalid/baseline/async-iterable-readonly.txt
- test/invalid/baseline/async-space-iterable.txt
- test/invalid/idl/argument-dict-default.webidl
- test/invalid/idl/argument-dict-nullable.webidl
- test/invalid/idl/argument-dict-optional.webidl
- test/invalid/idl/async-iterable-unterminated-args.webidl
- test/invalid/idl/async-space-iterable.webidl
- test/syntax/baseline/async-iterable.json
- test/syntax/idl/async-iterable.webidl
Implements the `async_iterable` part of https://github.com/whatwg/webidl/pull/1500.
> feat: implement new async_iterable syntax
